Refactor/rename lots of variables

diff --git a/safer b/safer
--- a/safer
+++ b/safer
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-safer_ver=0.0-dev
+version=0.0-dev
 
-safer_usage="Usage:
+usage="Usage:
 $0 [[OPTIONS] [<cmd> <image> [dir...]]]
 
 Arguments:
@@ -35,29 +35,29 @@ Config files: /etc/safer, ~/.saferrc, .saferrc"
 [ -e "$HOME/.saferrc" ] && . "$HOME/.saferrc"
 [ -e ".saferrc" ] && . ".saferrc"
 
-safer_dir=${SAFER_DIR:-.safer}
-safer_lib_path=${SAFER_LIB_PATH:-~/.local/share/safer:/usr/share/safer:/usr/local/share/safer}
-safer_inf_cmd="${SAFER_PERSIST_CMD:-sleep inf}"
-safer_inf_stop_cmd="${SAFER_PERSIST_STOP_CMD:---safer-stop}"
+script_dir=${SAFER_DIR:-.safer}
+lib_path=${SAFER_LIB_PATH:-~/.local/share/safer:/usr/share/safer:/usr/local/share/safer}
+persist_cmd="${SAFER_PERSIST_CMD:-sleep inf}"
+persist_stop_cmd="${SAFER_PERSIST_STOP_CMD:---safer-stop}"
 
 while getopts e:p:kn:d:R:X:K:S:fslivh opt
 do
 	case $opt in
-		e) safer_entrypoint=$OPTARG ;;
-		p) safer_port=$OPTARG ;;
-		k) safer_persist=1 ;;
-		n) safer_cname=$OPTARG ;;
-		d) safer_dir=$OPTARG ;;
-		R) safer_runtime_cmd=$OPTARG ;;
-		X) safer_opts_runtime_args=$OPTARG ;;
-		K) safer_inf_cmd=$OPTARG ;;
-		S) safer_inf_stop_cmd=$OPTARG ;;
-		f) safer_force=1 ;;
-		s) safer_skip_tty=1 ;;
-		l) safer_lib_tool=1 ;;
-		i) safer_lib_image=1 ;;
-		v) echo $safer_ver && exit ;;
-		h) echo "$safer_usage" && exit ;;
+		e) entrypoint=$OPTARG ;;
+		p) port=$OPTARG ;;
+		k) persist=1 ;;
+		n) container_name=$OPTARG ;;
+		d) script_dir=$OPTARG ;;
+		R) runtime_cmd=$OPTARG ;;
+		X) runtime_args=$OPTARG ;;
+		K) persist_cmd=$OPTARG ;;
+		S) persist_stop_cmd=$OPTARG ;;
+		f) force=1 ;;
+		s) skip_tty=1 ;;
+		l) lib_tool=1 ;;
+		i) lib_image=1 ;;
+		v) echo $version && exit ;;
+		h) echo "$usage" && exit ;;
 		*) ;;
 	esac
 done
@@ -66,32 +66,32 @@ shift $((OPTIND - 1))
 
 # Section 2: Library commands
 
-if [ $# -gt 0 ] && [ "${safer_lib_tool+x}" ] || [ "${safer_lib_image+x}" ]; then
-	safer_lib_item="$1"
+if [ $# -gt 0 ] && [ "${lib_tool+x}" ] || [ "${lib_image+x}" ]; then
+	item="$1"
 	shift 1
-	if [ "${safer_lib_tool+x}" ]; then
-		echo "$safer_lib_path" | while IFS=":" read -r location; do
-			if [ -e "$location/tools/$safer_lib_item" ]; then
-				sh "$location/tools/$safer_lib_item" "$@"
+	if [ "${lib_tool+x}" ]; then
+		echo "$lib_path" | while IFS=":" read -r location; do
+			if [ -e "$location/tools/$item" ]; then
+				sh "$location/tools/$item" "$@"
 				break
 			fi
 		done
 	fi
-	mkdir -p "$safer_dir/build"
-	if [ "${safer_lib_image+x}" ]; then
-		echo "$safer_lib_path" | while IFS=":" read -r location; do
-			if [ -e "$location/images/$safer_lib_item" ]; then
-				if [ -e "$safer_dir/build/$safer_lib_item" ]; then
-					echo "$safer_dir/build/$safer_lib_item already exists."
+	mkdir -p "$script_dir/build"
+	if [ "${lib_image+x}" ]; then
+		echo "$lib_path" | while IFS=":" read -r location; do
+			if [ -e "$location/images/$item" ]; then
+				if [ -e "$script_dir/build/$item" ]; then
+					echo "$script_dir/build/$item already exists."
 					exit 1
 				else
-					cp "$location/images/$safer_lib_item" "$safer_dir/build/$safer_lib_item"
+					cp "$location/images/$item" "$script_dir/build/$item"
 					break
 				fi
 			fi
 		done
-		if [ ! -e "$safer_dir/build/$safer_lib_item" ]; then
-			echo "$safer_lib_item image not found in library."
+		if [ ! -e "$script_dir/build/$item" ]; then
+			echo "$item image not found in library."
 			exit 1
 		fi
 	fi
@@ -101,59 +101,61 @@ fi
 # Section 3: Non-library execution, PATH definition and bad args exit
 
 if [ $# -gt 1 ]; then
-	safer_cmd="$1"
-	safer_image="$2"
+	tool="$1"
+	image="$2"
 	shift 2
 elif [ $# -eq 0 ]; then
-	printf 'PATH="%s:$PATH"\n' "$safer_dir"
+	printf 'PATH="%s:$PATH"\n' "$script_dir"
 	exit
 else
-	echo "$safer_usage"
+	echo "$usage"
 	exit 1
 fi
 
 # Section 4: Simple pre-processing of vars
 
-script_dest="$safer_dir/$safer_cmd"
-if [ -e "$script_dest" ] && [ -z "$safer_force" ]; then
+script_dest="$script_dir/$tool"
+if [ -e "$script_dest" ] && [ -z "$force" ]; then
 	echo "$script_dest already exists."
 	exit 1
 fi
 
-if [ -n "$safer_port" ]; then
-	case "$safer_port" in
-		*:*) safer_port_map="$safer_port" ;;
-		*) safer_port_map="$safer_port:$safer_port" ;;
+if [ -n "$port" ]; then
+	case "$port" in
+		*:*) port_map="$port" ;;
+		*) port_map="$port:$port" ;;
 	esac
 fi
 
-if [ "${safer_persist+x}" ] && [ -z "$safer_cname" ]; then
-	safer_cname_dir="$(echo "${PWD##*/}" | tr -cd '[:alnum:]')"
-	safer_cname="$safer_cmd-$safer_cname_dir"
+if [ "${persist+x}" ] && [ -z "$container_name" ]; then
+	clean_cmd="$(echo "${PWD##*/}" | tr -cd '[:alnum:]')"
+	container_name="$tool-$clean_cmd"
 fi
 
-if [ -z "${safer_runtime_cmd:=$SAFER_RT_CMD}" ]; then
+if [ -z "${runtime_cmd:=$SAFER_RT_CMD}" ]; then
 	if command -v podman >/dev/null 2>&1; then
-		safer_runtime_cmd=podman
+		runtime_cmd=podman
 	elif command -v docker >/dev/null 2>&1; then
-		safer_runtime_cmd=docker
+		runtime_cmd=docker
 	else
 		echo "Cannot detect a container runtime. See man page for more info."
 		exit 1
 	fi
 fi
 
-if [ "${safer_opts_runtime_args+x}" ]; then
-	safer_runtime_args="$safer_opts_runtime_args"
-elif [ "${SAFER_RT_ARGS+x}" ]; then
-	safer_runtime_args="$SAFER_RT_ARGS"
-elif [ "$safer_runtime_cmd" = "docker" ] || [ "$safer_runtime_cmd" = "sudo docker" ]; then
-	safer_runtime_args='--user "$(id -u):$(id -g)"'
+if [ ! "${runtime_args+x}" ]; then
+	if [ "${SAFER_RT_ARGS+x}"  ]; then
+		runtime_args=$SAFER_RT_ARGS
+	else
+		if [ "$runtime_cmd" = "docker" ] || [ "$runtime_cmd" = "sudo docker" ]; then
+			runtime_args='--user "$(id -u):$(id -g)"'
+		fi
+	fi
 fi
 
 # Section 5: Preprocessing of the original entrypoint parts
 
-if [ -n "$safer_cname" ]; then
+if [ -n "$container_name" ]; then
 	pad='\t'  # indent the original run lines on persistent scripts
 fi
 
@@ -165,15 +167,15 @@ for arg in "$@"; do
 done
 
 # Capture original image entrypoint and args
-if [ -n "$safer_cname" ] && [ -z "$safer_entrypoint" ]; then
+if [ -n "$container_name" ] && [ -z "$entrypoint" ]; then
 	set -f
 	IFS='
 '
 	# shellcheck disable=SC2046
 	set -- $(
-		$safer_runtime_cmd image inspect \
+		$runtime_cmd image inspect \
 		--format '{{range .Config.Entrypoint}}{{println .}}{{end}}' \
-		"$safer_image"
+		"$image"
 	)
 	unset IFS
 
@@ -196,7 +198,7 @@ script_file=$(mktemp)
 cwd=$(pwd -P)
 
 interactive_flag=-ti
-[ "${safer_skip_tty+x}" ] && interactive_flag=-i
+[ "${skip_tty+x}" ] && interactive_flag=-i
 
 {
 	printf '#!/bin/sh\n'
@@ -207,37 +209,37 @@ interactive_flag=-ti
 	printf '\t*) echo "safer: $0: outside project dir" 2>&1; exit 1 ;;\n'
 	printf 'esac\n'
 
-	if [ -n "$safer_cname" ]; then
-		printf 'if [ "$*" = "%s" ]; then\n' "$safer_inf_stop_cmd"
-		printf '\t%s kill %s\n' "$safer_runtime_cmd" "$safer_cname"
+	if [ -n "$container_name" ]; then
+		printf 'if [ "$*" = "%s" ]; then\n' "$persist_stop_cmd"
+		printf '\t%s kill %s\n' "$runtime_cmd" "$container_name"
 		printf '\texit\n'
 		printf 'fi\n'
-		printf 'if ! %s container inspect %s >/dev/null 2>&1; then\n' "$safer_runtime_cmd" "$safer_cname"
+		printf 'if ! %s container inspect %s >/dev/null 2>&1; then\n' "$runtime_cmd" "$container_name"
 	fi
 
-	if [ -n "$safer_cname" ]; then
-		printf '\t%s run --rm \\\n' "$safer_runtime_cmd"
+	if [ -n "$container_name" ]; then
+		printf '\t%s run --rm \\\n' "$runtime_cmd"
 	else
-		printf '%s run --rm %s \\\n' "$safer_runtime_cmd" "$interactive_flag"
+		printf '%s run --rm %s \\\n' "$runtime_cmd" "$interactive_flag"
 	fi
 
-	if [ -n "$safer_runtime_args" ]; then
-		printf '%b\t%s \\\n' "$pad" "$safer_runtime_args"
+	if [ -n "$runtime_args" ]; then
+		printf '%b\t%s \\\n' "$pad" "$runtime_args"
 	fi
 
-	if [ -n "$safer_cname" ]; then
+	if [ -n "$container_name" ]; then
 		printf '\t\t--entrypoint '\'''\'' \\\n'
-	elif [ -n "$safer_entrypoint" ]; then
-		printf '\t--entrypoint '\''%s'\'' \\\n' "$safer_entrypoint"
+	elif [ -n "$entrypoint" ]; then
+		printf '\t--entrypoint '\''%s'\'' \\\n' "$entrypoint"
 	fi
 
-	if [ -n "$safer_port_map" ]; then
-		printf '%b\t-p "%s" \\\n' "$pad" "$safer_port_map"
+	if [ -n "$port_map" ]; then
+		printf '%b\t-p "%s" \\\n' "$pad" "$port_map"
 	fi
 
 	printf '%b\t-v "%s":"%s" \\\n' "$pad" "$cwd" "$cwd"
 
-	if [ -n "$safer_cname" ]; then
+	if [ -n "$container_name" ]; then
 		printf '\t\t-w "$project_dir"'
 	else
 		printf '\t-w "$(pwd -P)"'
@@ -245,34 +247,34 @@ interactive_flag=-ti
 
 	printf '%s' "$extra_volumes"
 
-	if [ -n "$safer_cname" ]; then
-		printf ' \\\n\t\t-d --name "%s" \\\n' "$safer_cname"
+	if [ -n "$container_name" ]; then
+		printf ' \\\n\t\t-d --name "%s" \\\n' "$container_name"
 	else
 		printf ' \\\n'
 	fi
 
-	if [ -n "$safer_cname" ]; then
-		printf '\t\t%s %s\n' "$safer_image" "$safer_inf_cmd"
+	if [ -n "$container_name" ]; then
+		printf '\t\t%s %s\n' "$image" "$persist_cmd"
 	else
-		printf '\t%s "$@"\n' "$safer_image"
+		printf '\t%s "$@"\n' "$image"
 	fi
 
-	if [ -n "$safer_cname" ]; then
+	if [ -n "$container_name" ]; then
 		printf 'fi\n'
-		printf '%s exec %s \\\n' "$safer_runtime_cmd" "$interactive_flag"
-		if [ -n "$safer_runtime_args" ]; then
-			printf '\t%s \\\n' "$safer_runtime_args"
+		printf '%s exec %s \\\n' "$runtime_cmd" "$interactive_flag"
+		if [ -n "$runtime_args" ]; then
+			printf '\t%s \\\n' "$runtime_args"
 		fi
 		printf '\t-w "$(pwd -P)" \\\n'
-		if [ -n "$safer_entrypoint" ]; then
-			printf '\t%s '\''%s'\'' "$@"\n' "$safer_cname" "$safer_entrypoint"
+		if [ -n "$entrypoint" ]; then
+			printf '\t%s '\''%s'\'' "$@"\n' "$container_name" "$entrypoint"
 		else
 			if [ -z "$og_entrypoint" ]; then
-				printf '\t%s "$@"\n' "$safer_cname"
+				printf '\t%s "$@"\n' "$container_name"
 			elif [ -z "$og_exec_args" ]; then
-				printf '\t%s '\''%s'\'' "$@"\n' "$safer_cname" "$og_entrypoint"
+				printf '\t%s '\''%s'\'' "$@"\n' "$container_name" "$og_entrypoint"
 			else
-				printf '\t%s '\''%s'\'' %s "$@"\n' "$safer_cname" "$og_entrypoint" "$og_exec_args"
+				printf '\t%s '\''%s'\'' %s "$@"\n' "$container_name" "$og_entrypoint" "$og_exec_args"
 			fi
 		fi
 	fi
