Implement library commands -l -i

diff --git a/safer b/safer
--- a/safer
+++ b/safer
@@ -18,6 +18,8 @@ Options:
  -k          Use this name to persist the container.
  -f          Force script replacement.
  -s          Skip container pseudo-tty allocation.
+ -l          Get the tool definition from the library.
+ -i          Install a Containerfile from the library.
  -v          Display the current version.
  -h          Display usage and exit.
 
@@ -33,14 +35,13 @@ Config files: /etc/safer, ~/.saferrc, .saferrc"
 [ -e ".saferrc" ] && . ".saferrc"
 
 safer_dir=${SAFER_DIR:-.safer}
+safer_lib_path=${SAFER_LIB_PATH:-~/.local/share/safer:/usr/share/safer:/usr/local/share/safer}
 safer_inf_cmd="${SAFER_PERSIST_CMD:-sleep inf}"
 safer_inf_stop_cmd="${SAFER_PERSIST_STOP_CMD:---safer-stop}"
 
-while getopts vhe:p:k:d:R:X:K:S:fs opt
+while getopts e:p:k:d:R:X:K:S:fslivh opt
 do
 	case $opt in
-		v) echo $safer_ver && exit ;;
-		h) echo "$safer_usage" && exit ;;
 		e) safer_entrypoint=$OPTARG ;;
 		p) safer_port=$OPTARG ;;
 		k) safer_inf=$OPTARG ;;
@@ -51,11 +52,51 @@ do
 		S) safer_inf_stop_cmd=$OPTARG ;;
 		f) safer_force=1 ;;
 		s) safer_skip_tty=1 ;;
+		l) safer_lib_tool=1 ;;
+		i) safer_lib_image=1 ;;
+		v) echo $safer_ver && exit ;;
+		h) echo "$safer_usage" && exit ;;
 		*) ;;
 	esac
 done
 
 shift $((OPTIND - 1))
+
+# Section 2: Library commands
+
+if [ $# -gt 0 ] && [ "${safer_lib_tool+x}" ] || [ "${safer_lib_image+x}" ]; then
+	safer_lib_item="$1"
+	shift 1
+	if [ "${safer_lib_tool+x}" ]; then
+		echo "$safer_lib_path" | while IFS=":" read -r location; do
+			if [ -e "$location/tools/$safer_lib_item" ]; then
+				sh "$location/tools/$safer_lib_item" "$@"
+				break
+			fi
+		done
+	fi
+	mkdir -p "$safer_dir/build"
+	if [ "${safer_lib_image+x}" ]; then
+		echo "$safer_lib_path" | while IFS=":" read -r location; do
+			if [ -e "$location/images/$safer_lib_item" ]; then
+				if [ -e "$safer_dir/build/$safer_lib_item" ]; then
+					echo "$safer_dir/build/$safer_lib_item already exists."
+					exit 1
+				else
+					cp "$location/images/$safer_lib_item" "$safer_dir/build/$safer_lib_item"
+					break
+				fi
+			fi
+		done
+		if [ ! -e "$safer_dir/build/$safer_lib_item" ]; then
+			echo "$safer_lib_item image not found in library."
+			exit 1
+		fi
+	fi
+	exit
+fi
+
+# Section 3: Non-library execution, PATH definition and bad args exit
 
 if [ $# -gt 1 ]; then
 	safer_cmd="$1"
@@ -69,7 +110,7 @@ else
 	exit 1
 fi
 
-# Section 2: Preprocessing of variables
+# Section 4: Simple pre-processing of vars
 
 script_dest="$safer_dir/$safer_cmd"
 if [ -e "$script_dest" ] && [ -z "$safer_force" ]; then
@@ -103,7 +144,7 @@ elif [ "$safer_runtime_cmd" = "docker" ] || [ "$safer_runtime_cmd" = "sudo docke
 	safer_runtime_args='--user "$(id -u):$(id -g)"'
 fi
 
-# Section 3: Preprocessing of the original entrypoint parts
+# Section 5: Preprocessing of the original entrypoint parts
 
 if [ -n "$safer_inf" ]; then
 	pad='\t'  # indent the original run lines on persistent scripts
@@ -142,7 +183,7 @@ if [ -n "$safer_inf" ] && [ -z "$safer_entrypoint" ]; then
 	fi
 fi
 
-# Section 4: Writing the script
+# Section 6: Writing the script
 
 script_file=$(mktemp)
 cwd=$(pwd -P)
